openapi: 3.0.0
info:
  title: Hive
  version: '1.0'
servers:
  - url: 'https://localhost:5001'
paths:
  /users:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-users
  '/users/{userId}':
    parameters:
      - schema:
          type: string
        name: userId
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    type: string
              examples: {}
      operationId: get-users-userId
components:
  schemas: {}
